### ISSUE TITLE
Game crashes while authorizing

### ISSUE THREAD

**Issue by TheXe0N** [Elringus/UnityGoogleDrive#111]
I'm using a Lenovo Tab M10 (third gen) and whatever configuration I use, it crashes. I have also used the same configuration with Samsung phones/tablets and they authorize just fine.

03-09 21:25:12.600: W/ActivityTaskManager(1006):   Force finishing activity com.elringus.naninovelsandbox/com.unity3d.player.UnityPlayerActivity

I get many logs but this is the only warning I get. Other logs also mention things about being focused. I have no idea why this happens. The appauth plugin's version is 0.7.1 and I'm using Unity 2020.3.42f1. I'm also sure that the API-related stuff is set correctly as the app works in Samsung devices.

**Comment by TheXe0N** [comment]
Also, this is definitely not caused by my game, as I used the example project.

**Comment by DwikyAnderson** [comment]
i also have same problem here
