### ISSUE TITLE
403 error: The request is missing a valid API key

### ISSUE THREAD

**Issue by Elringus** [Elringus/UnityGoogleDrive#114]
### Discussed in https://github.com/Elringus/UnityGoogleDrive/discussions/113

<div type='discussions-op-text'>

<sup>Originally posted by **ConnKing** March 29, 2023</sup>
I ran through the setup guide and tried the .json OAuth 2.0 Client ID files for both Desktop and Web application with http://localhost listed in under my Authorized redirect URIs.
The values seem to be getting set correctly in the window
<img width="658" alt="image" src="https://user-images.githubusercontent.com/110412626/228373876-a8174e83-cf92-4fae-80b0-cb48ecdb108c.png">

Then on start I call:
```
 void Start()
    {
        // Listing files.
        GoogleDriveFiles.List().Send().OnDone += fileList => {
            var files = fileList.Files;
            foreach (var f in files)
            {
                Debug.Log(f);

            }
        };
}

```
When I click run in the editor with the script attached to a GameObject in the scene. It gives me this error:
**UnityGoogleDrive: HTTP/1.1 403 Forbidden**
**Google Drive API Error Description: Code '403' Message: 'The request is missing a valid API key.'**
 **- Domain: 'global' Reason: 'forbidden' Message: 'The request is missing a valid API key.' LocationType: '' Location: ''**
 
 the uri listed with the error is https://www.googleapis.com/drive/v3/files

Is there something I'm missing? Any help would be appreciated.</div>

**Comment by Elringus** [comment]
Probably something has changed on Google side, not sure what exactly, though.

**Comment by Elringus** [comment]
https://support.google.com/drive/thread/164574510/403-forbidden-when-the-app-tries-to-dowload-the-file-from-google-drive?hl=en

**Comment by Elringus** [comment]
If anyone have any idea what could've caused this, please let us know here.

**Comment by Elringus** [comment]
Ok, so re-creating the credentials on the google app dashboard helped. For one of my projects I also had to do the following before using the APIs:

```csharp
public class InitializeGoogleDrive : MonoBehaviour
{
    private IEnumerator Start ()
    {
        AuthController.RefreshAccessToken();
        while (AuthController.IsRefreshingAccessToken)
            yield return null;
        // ... now it's safe to use the APIs
    }
}
```
All the tests from this projects seem to be working fine w/o any changes, though.

**Comment by dustinkerstein** [comment]
FYI, I'm also running into this same issue after having UnityGoogleDrive working in production for 1+ years. I quickly tried creating new OAuth credentials, but that didn't seem to help. I'll try the yield approach later today, but do you have any other ideas on how to handle this?

**Comment by dustinkerstein** [comment]
Adding the `RefreshAccessToken` code above seems to fix the issue. Thanks!

**Comment by yoiang** [comment]
Refreshing the access token worked for me as well, it would be lovely to include in the README!
