### ISSUE TITLE
ActivityNotFoundException on Android SDK 30

### ISSUE THREAD

**Issue by DLohn** [Elringus/UnityGoogleDrive#117]
Duplicate of #92, #93, #103

As in, the exact same ActivityNotFoundExceptions on Android are observed on Android SDK version 30.
I think an update to the readme explaining Android SDK must be 29 or under would be helpful until the underlying issue is resolved.

**Comment by monurgungor** [comment]
Hey, have you ever found a solution to this?

**Comment by monurgungor** [comment]
Hey, were you able to make it work under Android SDK 29?

**Comment by DLohn** [comment]
Yes, it worked on Android SDK 29, at least on the Android device I was sending the builds to.
