### ISSUE TITLE
Only I can upload to my Drive

### ISSUE THREAD

**Issue by CharalamposGeorgiadis** [Elringus/UnityGoogleDrive#123]
Hello. I am making a Unity game puzzle game which retains some player data during gameplay. I want to be able to have all player data in one single file online so that I can use it to train a player modeling model. My issue is that the data is only being uploaded to my drive if I am using the google account I used to set up the corresponding google cloud project. If someone else plays the game from their own pc, they can download the contents of the file, but nothing happens when the game should upload the updated contents to my Drive. Can you help me identify what I might have done wrong? My file retrieval/uploading code is below:

```
    IEnumerator CheckAndUploadCSV(List<string> csvData, string filename, string file_id)
    {
        var request_download = GoogleDriveFiles.Download(file_id);
        yield return request_download.Send();

        string downloadedContent;
        if (!request_download.IsError)
        {
            downloadedContent = Encoding.UTF8.GetString(request_download.ResponseData.Content);
            gameEnded.GetComponent<TextMeshProUGUI>().text = downloadedContent;
            string fileData = downloadedContent + Environment.NewLine + string.Join(Environment.NewLine, csvData.Skip(1));
            byte[] byteArray = Encoding.UTF8.GetBytes(fileData);
            var file = new UnityGoogleDrive.Data.File() { Name = filename, Content = byteArray };
            var request_update = GoogleDriveFiles.Update(file_id, file);
            yield return request_update.Send();
        }
        else
        {
            string fileData = string.Join(Environment.NewLine, csvData);
            byte[] byteArray = Encoding.UTF8.GetBytes(fileData);
            var file = new UnityGoogleDrive.Data.File() { Name = filename, Content = byteArray };
            var request_create = GoogleDriveFiles.Create(file);
            request_create.Fields = new List<string> { "id" };
            yield return request_create.Send();
        }
    }
```

**Comment by Elringus** [comment]
Google drive is not a DB, but a personal cloud storage; check this out: https://github.com/Elringus/UnityGoogleDrive#is-it-possible-for-users-to-access-my-google-drive-account-and-use-it-as-a-database-for-my-app

**Comment by CharalamposGeorgiadis** [comment]
> Google drive is not a DB, but a personal cloud storage; check this out: https://github.com/Elringus/UnityGoogleDrive#is-it-possible-for-users-to-access-my-google-drive-account-and-use-it-as-a-database-for-my-app

I understand that. I thought that the OAuth authentication allowed for others to upload to my drive, but I must have been wrong
