### ISSUE TITLE
Add Exceptions to Async

### ISSUE THREAD

**Issue by DavidJH2** [elringus/UnityGoogleDrive#124]
Currently in the Async methods, errors are quietly eaten. In my case I need to know when an error, such as 'can't resolve host', has occurred.

**Comment by Elringus** [comment]
Make sure to await the result if you want to catch the exceptions.

**Comment by DavidJH2** [comment]
> Make sure to await the result if you want to catch the exceptions.

Sorry for the late reply.

The problem is that there is no exception to catch even if you await.

For example: if Helpers.ValidatePath() detects an error it simple returns null which could mean anything: file not found, cant connect to server, etc...

It would be nice if it would either generate an exception or at least pass on the error code. As it is it simply eats the error code. Since this is a package, you can't modify it. So instead you have to make a copy and modified the copy.
