### ISSUE TITLE
Add Google Drive change events

### ISSUE THREAD

**Issue by DavidJH2** [elringus/UnityGoogleDrive#125]
Would it be possible to add Google Drive change events to avoid having to poll the Google Drive for changes on the Google Drive side?

**Comment by elringus** [comment]
Do they provide an API for that?

**Comment by DavidJH2** [comment]
Yes: https://developers.google.com/drive/api/guides/push

Though, I don't know enough to know if it is applicable here

**Comment by DavidJH2** [comment]
> Do they provide an API for that?

Yes: https://developers.google.com/drive/api/guides/push

Though, I don't know enough to know if it is applicable here

**Comment by elringus** [comment]
You'd need to run your custom server/endpoint to receive google's notifications and propagate notifications to the devices yourself.

**Comment by DavidJH2** [comment]
> You'd need to run your custom server/endpoint to receive google's notifications and propagate notifications to the devices yourself.

That's what I had suspected. Maybe a Unity Server?

Oh, wait, what about this: https://developers.google.com/drive/api/reference/rest/v3/changes/watch

**Comment by elringus** [comment]
They require https endpoint to call back to, so it won't work with a unity build/server. Basically, you have to maintain custom web app, that will invoke the watch endpoint you've mentioned to receive callbacks. You'll then have to manage connections with the clients to push/route notifications to them.

**Comment by DavidJH2** [comment]
> They require https endpoint to call back to, so it won't work with a unity build/server. Basically, you have to maintain custom web app, that will invoke the watch endpoint you've mentioned to receive callbacks. You'll then have to manage connections with the clients to push/route notifications to them.

Are you sure? I under stand that Notifications require this, but changes.watch (https://developers.google.com/drive/api/reference/rest/v3/changes/watch) seems to to have the same Request method as files.list for instance.

In fact I wonder if it's not already available?
