### ISSUE TITLE
Google sign loopback authorization system deprecated

### ISSUE THREAD

**Issue by cdecron** [elringus/UnityGoogleDrive#126]
Hello,
As said in title, the loopback authorization system is deprecated.
UnityGoogleDrive plugin is still working for Android, however we can't end the autorization system on Windows, for example to test in the Unity player.

Here is the error message (in French, sorry...):
![image](https://github.com/elringus/UnityGoogleDrive/assets/6977299/6cbc078a-7191-473b-b290-1de279ea85c8)

It sends to [the migration page](https://developers.google.com/identity/protocols/oauth2/resources/loopback-migration), but no solution for Desktop app is shown.

Do you know some ways to make it work?

Thank you

**Comment by elringus** [comment]
No idea. If someone happen to know, please share.

**Comment by elringus** [comment]
I've just checked and loopback is working fine for me in editor and in Windows standalone build. The article you've mentioned is only about mobiles. We've been using native auth libs on mobiles from the start, so this change doesn't seem to affect the plugin at all.

**Comment by elringus** [comment]
![67087b9b5fe0015b64ffbae3eee47cad](https://github.com/elringus/UnityGoogleDrive/assets/2056864/da3c09cd-eb28-46cf-9cd1-71516e316479)

**Comment by DavidJH2** [comment]
I also am able to Authorize through Windows with Chrome

I don't remember the specifics, but I believe that Android, Web, and Windows each have a different way of Authorizing. I believe that when you connect your app to Google Cloud, you have to set one up for iOS (not Android even if your using Android) and another for Windows. It's in the setup procedure for this UnityGoogleDrive API package.

Maybe there is a mistake in the setup for Windows.

***************************************************************************************************
Another thing to consider is maybe you should go back to the Older oAuth;
I'm still using 0.7.+ / 1.3.0 and it works fine, maybe it's only depreciated in the new oath
***************************************************************************************************

**Comment by cdecron** [comment]
Hello,
Excuse me, you're right! There was a problem with my setup on Windows, the json used was the wrong one.
However, this rises another question: every time you switch platform, do you have to go to "Projet settings" > "Google Drive" and modify information?
There isn't any automatic system which recognizes on which platform you are and uses corresponding Goole API information?

Thank you

**Comment by DavidJH2** [comment]
Awesome!

You don't have to switch the settings each time you change platforms..

You set up both iOS AND Windows and it picks the right one

I had to go through the set-up procedure 2 or three times before I got it right.

**Comment by cdecron** [comment]
Thank you for you answer, however I'm not sure to understand.
I have two OAuth ID clients, one for Android and one for desktop app.
If I put the one for desktop app in Unity Google Drive settings, you say that it keeps in memory the one for Android if it had been entered before?
