### ISSUE TITLE
Support for resumable uploads?

### ISSUE THREAD

**Issue by josephnarai** [Elringus/UnityGoogleDrive#13]
Might be a silly question, but I can't figure out if this supports resumable uploads? If it does, could someone post an example?

Thanks

Joe

**Comment by Elringus** [comment]
It's currently using simple multipart uploads. I've been planning to implement support for [resumable uploads](https://developers.google.com/drive/api/v3/resumable-upload), so I'll leave this issue open until it's done.

**Comment by Elringus** [comment]
Resumable uploads are now supported with the [latest release](https://github.com/Elringus/UnityGoogleDrive/releases/tag/v0.13-alpha). 

For usage example see: https://github.com/Elringus/UnityGoogleDrive/blob/master/Assets/Scripts/TestFilesCreateResumable.cs

**Comment by josephnarai** [comment]
Thanks for the quick implementation - much appreciated.

However, I believe some changes are required. The main reason for using resumable uploads is to be able to upload a very large file in small data chunks. Your current implementation, while supporting resumable mode, doesn't achieve that, as you are sending all the data in a single command, which means if that command fails, it will have to upload all of the data again.

**Comment by Elringus** [comment]
I'm not using a chunked transfer mode, as [Google recommends against it](https://developers.google.com/drive/api/v3/resumable-upload#upload-resumable). The only reason this mode could be preferred (judging by the docs) is a fixed time limit for individual requests. But even then, if the request will time-out, the upload won't begin from the start in the subsequent one. In the current implementation, when a resumable session URI is provided, the upload will only send the remaining data. You can test it in the example I've shared in the previous message. Just begin uploading a large file and then either press "Abort" button to abort the request or physically interrupt the network (without exiting the play mode); then reconnect and press "Send" again -- the upload will start from the point it was at before the disconnect.

**Comment by josephnarai** [comment]
Hrm. Well, if you have a large file that can not fit into memory (which I do), then this method can not work. You must be able to send the data in smaller chunks - reading some data from the file and sending it up, then on completion sending the next etc. 
Please advise how we can implement uploads of very large files with your current implementation.

**Comment by josephnarai** [comment]
Actually - I have another question for you regarding this - the same issue occurs with the download command? When we receive the content, we get all the data.... what are we supposed to do for receiving very large files? Maybe I won't have an issue... ?? I'm implementing my application now, so I'll let you know if I run into memory limitations....

**Comment by Elringus** [comment]
Ah, I didn't consider the memory, my bad. I guess, there should be a way to allow users to stream the file's data (both up and down) to the drive independently of the metadata API calls, so it'll be possible to use any type of caching or sequential reading to preserve memory usage. I've added a new issue for this matter (#15).

**Comment by josephnarai** [comment]
Thanks - I appreciate the effort!! It's a great plugin you have created!

**Comment by josephnarai** [comment]
One more question - does you plugin allow concurrent downloads? OR do they need to be sequential - request download - wait for compelte - request download wait ... etc.?

**Comment by Elringus** [comment]
You can start any number of concurrent requests. Although make sure to check quota settings in the console app, as it may limit the allowed amount of requests per user per second.

**Comment by josephnarai** [comment]
Hrm - yes, I ran into quota issues as well as null references in your code... so I've currently made it sequential which is fine for my application --- I may experiment with adding some concurrency .... but it's working beautifully !! Thanks again for the great plugin and for taking the time to answer my questions! Much appreciated!!!

Joe
