### ISSUE TITLE
Chunked download and upload file's content

### ISSUE THREAD

**Issue by Elringus** [Elringus/UnityGoogleDrive#15]
There should be a way to allow users to stream the file's data (both up and down) to the drive independently of the metadata API calls, so it'll be possible to use any type of caching or sequential reading to preserve memory usage.

**Comment by Elringus** [comment]
Chunked download and uploads are now supported with the [latest release](https://github.com/Elringus/UnityGoogleDrive/releases/tag/v0.14-alpha).

To perform a partial download you have to supply `downloadRange` agrument for the `GoogleDriveFiles.Download` request specifying the bytes range you wish to get. Here is an [example script for a partial text file download](https://github.com/Elringus/UnityGoogleDrive/blob/master/Assets/Scripts/TestFilesDownloadRange.cs). More info on partial downloads can be found in the [API docs](https://developers.google.com/drive/api/v3/manage-downloads#partial_download).

For the chunked uploads you'll have to use resumable upload requests in a special manner. First, create a resumable upload request (via either `GoogleDriveFiles.CreateResumable` or `GoogleDriveFiles.UpdateResumable`), supply the file's metadata, but don't set the file's content. Send the request and get a resumable session URI from the response. Now you can use the session URI to upload the file's content in chunks. [See the Drive API docs](https://developers.google.com/drive/api/v3/resumable-upload#upload-resumable) for detailed instructions on how to perform a chunked upload using a resumable session URI.

**Comment by Elringus** [comment]
You can use this example of a resumable upload: https://github.com/Elringus/UnityGoogleDrive/blob/master/Assets/Scripts/TestFilesCreateResumable.cs#L43

It's all the same, just don't set `Content` field for the `UnityGoogleDrive.Data.File` class. You'll still receive a `resumableSessionUri` this way, but then you'll have to upload the actual content of the file yourself using the scheme described in the google drive docs.

**Comment by josephnarai** [comment]
I've created the resumable upload session, that's not the problem, it's which commands should be used to upload the chunk? Are you saying that direct PUT commands have to be used? Or can the chunk be uploaded using other commands in your library? I'm clearly missing something obvious.

**Comment by Elringus** [comment]
The chunked upload process itself has nothing to do with the library. You can use any regular HTTP requests (either from the .NET System.Net namespace, Unity's wrappers or any other options, it doesn't matter). In this process you won't need any Google Drive -specific data (like oauth credentials), just the resumable upload session URI.

**Comment by josephnarai** [comment]
Oh I see - I'll take a look at implementing that then - but I would think it would make sense to include this functionality in your library - to me it seems incomplete. Surely it should just be another call with the appropriate range parameters, just like you have implemented chunked downloads ... seems strange to me to have to go to use a different system for a core function...

**Comment by Elringus** [comment]
Well, pull requests are always welcome ;)

**Comment by josephnarai** [comment]
I used your library because I didn't want to have to implement the raw html. I'd be happy to pay you for the library (you should put it on the Unity Asset Store) ... and I'll be happy to pay you to implement this feature too (I'm sure you'll be able to implement this much faster than I would - particularly if I have to go through and understand your low level implementation). Let me know how much it would be.

**Comment by Elringus** [comment]
Sure, please contact me via elringus[at]gmail.com and we'll discuss the details.
