### ISSUE TITLE
AppData

### ISSUE THREAD

**Issue by TwerkyMan** [Elringus/UnityGoogleDrive#16]
Hello, i just have one question: is it possible to upload to and/or download from appdata folder in google drive? Thanks in advance :)

**Comment by Elringus** [comment]
Hi! Sure, just use `appDataFolder` alias to reference the appdata folder. Eg, to create a file in the appdata folder, add `appDataFolder` item to the File.Parents list. More info: https://developers.google.com/drive/api/v3/appdata
