### ISSUE TITLE
Add an option to request `drive.appdata` scope to access AppData folder

### ISSUE THREAD

**Issue by TwerkyMan** [Elringus/UnityGoogleDrive#17]
Hello again, I'm not trying to be annoying, but i've spent some time trying to figure out how appdata folder works. In unity it shows me bunch of errors when i try to list of upload a file to drive. I've read that you need to request appdata scope in order to access it. I'm just wondering, perhaps you could help me figure this out, because I'm really not good with Goole Drive stuff yet :) Thanks in advance.

**Comment by Elringus** [comment]
Can you please describe what exactly you're doing and what errors you get? Also, take a look at the [test and example scripts](https://github.com/Elringus/UnityGoogleDrive/tree/master/Assets/Scripts), they could help you to get started.

Btw, you can still reply to the closed issues in case you have further questions, so no need to create duplicates :)

**Comment by TwerkyMan** [comment]
Okay, didn't know the thing about duplicates, sorry :) So what I'm trying to do is basicly list files in drive, upload a file in appdata folder and, later on, if needed - download it. The errors i get when i try to list the files : 

UnityGoogleDrive: Generic/unknown HTTP errorThe granted scopes do not give access to all of the requested spaces.
UnityEngine.Debug:LogError(Object)
UnityGoogleDrive.GoogleDriveRequest`1:HandleWebRequestDone(AsyncOperation) (at Assets/UnityGoogleDrive-master/Assets/UnityGoogleDrive/Runtime/GoogleDriveRequest.cs:229)
UnityEngine.AsyncOperation:InvokeCompletionEvent()

ArgumentException: JSON parse error: Invalid value.
UnityEngine.JsonUtility.FromJson (System.String json, System.Type type) (at C:/buildslave/unity/build/Modules/JSONSerialize/Public/JsonUtility.bindings.cs:50)
UnityEngine.JsonUtility.FromJson[GoogleDriveResponseError] (System.String json) (at C:/buildslave/unity/build/Modules/JSONSerialize/Public/JsonUtility.bindings.cs:33)
UnityGoogleDrive.GoogleDriveRequest`1[TResponse].HandleResponseData (UnityEngine.Networking.DownloadHandler downloadHandler) (at Assets/UnityGoogleDrive-master/Assets/UnityGoogleDrive/Runtime/GoogleDriveRequest.cs:182)
UnityGoogleDrive.GoogleDriveRequest`1[TResponse].HandleWebRequestDone (UnityEngine.AsyncOperation requestYeild) (at Assets/UnityGoogleDrive-master/Assets/UnityGoogleDrive/Runtime/GoogleDriveRequest.cs:227)
UnityEngine.AsyncOperation.InvokeCompletionEvent () (at C:/buildslave/unity/build/Runtime/Export/AsyncOperation.cs:21)

UnityGoogleDrive: Generic/unknown HTTP errorThe granted scopes do not allow use of the Application Data folder.
UnityEngine.Debug:LogError(Object)
UnityGoogleDrive.GoogleDriveRequest`1:HandleWebRequestDone(AsyncOperation) (at Assets/UnityGoogleDrive-master/Assets/UnityGoogleDrive/Runtime/GoogleDriveRequest.cs:229)
UnityEngine.AsyncOperation:InvokeCompletionEvent()

**Comment by Elringus** [comment]
Looks like the default scope isn't enough to access the app data. Guess I'll add a setting to include `drive.appdata` scope when required. I'll leave this issue until it's done. Thank you for sharing the info!

**Comment by Elringus** [comment]
Scope to access AppData folder will now be requested by default with the [latest release](https://github.com/Elringus/UnityGoogleDrive/releases/tag/v0.15-alpha).

Make sure to delete cached auth tokens to force a new auth request and get required scopes.
