### ISSUE TITLE
DownloadRequest Progress not working

### ISSUE THREAD

**Issue by josephnarai** [Elringus/UnityGoogleDrive#19]
I'm downloading my large files in 512k chunks. I'm using DownloadRequest.Progress to monitor progress of the chunk download every second. The issue is that Progress remains a zero for the entire chunk download (sometimes up to 10 or more seconds worth), only occasionally do I get a non zero value as the last very last Progress reading before the chunk download is actauly completed.

I'm using WebRequest.uploadProgress for monitoring upload progress for each chunk and it's working perfectly.

Is Progress implemented correctly? Is there a reason it's not reporting progress over the course of the download?

**Comment by Elringus** [comment]
I've just tested it using the [download range example](https://github.com/Elringus/UnityGoogleDrive/blob/master/Assets/Scripts/TestFilesDownloadRange.cs) and looks like it's working fine: https://i.gyazo.com/3d250f03ad5338db387accb1356da7c8.mp4

Be aware, that the progress property of the download request indicates only the download progress, but the request also spends a while communicating with the API before the download starts. Maybe it's just in your case the request spends most of the time communicating and the download itself is very fast, so you get this instant 0-1 values.

**Comment by josephnarai** [comment]
That must be it. My chunks are only 512k ... so it's downloading in less than 1 second but it spends up to 10 seconds (or more) doing the communication before the download!.... It doesn't matter much - I just don't like the UI looking like it's frozen for that long a time ...
