### ISSUE TITLE
The type or namespace name `Data' could not be found. Are you missing an assembly reference?

### ISSUE THREAD

**Issue by JanaJarecki** [Elringus/UnityGoogleDrive#2]
Hi,
when trying to run the test code

        var file = new Data.File() { Name = "Image.png", Content = rawImageData, MimeType = "image/png" };
        GoogleDriveFiles.Create(file).Send();

, unity complains "The type or namespace name `Data' could not be found. Are you missing an assembly reference?"

My script adds the namespaces

using System.Data;
using Mono.Data.Sqlite;
using Mono.Data.SqliteClient;

Can you maybe point me to a solution?

**Comment by JanaJarecki** [comment]
Solved it by using

`UnityGoogleDrive.Data.File()`

**Comment by Elringus** [comment]
My bad, the example code was taken from the internal namespace and is quite confusing; fixed that.

You can either use full path to the SDK data types (like you did) or include UnityGoogleDrive.Data namespace.
