### ISSUE TITLE
Redirect

### ISSUE THREAD

**Issue by TwerkyMan** [Elringus/UnityGoogleDrive#20]
Hello. I've been using this plugin for a while now, and I have to say it works like a charm. I just wanted to ask is there a way to redirect the user back to the application after login? Thanks in advance :)

**Comment by Elringus** [comment]
Hi! You can find info about the possible auto-redirection options in the FAQ here: https://github.com/Elringus/UnityGoogleDrive#is-there-a-way-to-automatically-redirect-user-to-the-app-when-authorization-in-browser-is-complete I hadn't tested it myself, so it's all in theory. If you'll manage to make it work, please let me know :)
