### ISSUE TITLE
UWP Hololens issues

### ISSUE THREAD

**Issue by 7ail** [Elringus/UnityGoogleDrive#22]
Hi Elringus

I'm currently trying to create an AR unity project that will run on the Hololens with Google Drive integration.

After I downloaded a zip of your repo, I tried building the project as:
PC, Mac, & Linux Standalone
This option works and i was able to generate an .exe file

However, when I changed the platform to UWP specialising in hololens, I received errors such as the one below:

![capture](https://user-images.githubusercontent.com/26154804/44040240-1cd673ca-9f5e-11e8-8b8f-786b26c732d5.PNG)

Was just wondering if the UnityGoogleDrive is compatible with AR focused projects?

**Comment by Elringus** [comment]
Hi, Please try to switch to [IL2CPP backend](https://docs.unity3d.com/Manual/windowsstore-scriptingbackends.html), as the .NET one seems to use a stripped version of the core class libraries.

**Comment by 7ail** [comment]
Hi, I tried switching to IL2CPP and I got the following issues

![settings](https://user-images.githubusercontent.com/26154804/44042513-ccee8cde-9f63-11e8-9c20-6b554e1b193f.PNG)
![error](https://user-images.githubusercontent.com/26154804/44042519-cf71f0a4-9f63-11e8-8feb-bd56b2491655.PNG)

Is there something else that needs to be done? Once again thanks for helping me troubleshoot my problem

**Comment by Elringus** [comment]
Try switching to .NET 4.6 scripting runtime.

**Comment by 7ail** [comment]
Hi Elringus,

I've managed to compile/build from unity using IL2CPP and .Net 4.6. However, there may be some compatibility issues running it on the Hololens due to its lack of support for IL2CPP. I'll continue working on it and update this post once I get something more concrete.

Thanks again for your help.

**Comment by Elringus** [comment]
Hey there! I haven't heard from you for a while, so I'll close the issue for now. In case you still have any problems with the subject, feel free to respond here and I'll re-open the issue.

**Comment by 7ail** [comment]
Hi Elringus,

Sorry for not posting a follow up. Unfortunately I was not able to deploy it to the hololens due to the discrepancies between the unity .Net scripting backend version and hte version that is compatible with Hololens.

This meant that dependencies needed to fix the aforementioned problem is not available. There seems to be work around for this but I was unable to come up with a solution.
