### ISSUE TITLE
iOS Authentication Issues

### ISSUE THREAD

**Issue by ddutchie** [Elringus/UnityGoogleDrive#24]
Hello Elringus.

I am getting this error when running on iOS.

`UnityGoogleDrive: Failed to execute authorization procedure. Check application settings and credentials.
UnityGoogleDrive.AuthController:HandleAccessTokenProviderDone(IAccessTokenProvider)
UnityEngine.AsyncOperation:InvokeCompletionEvent()`

Settings are correct as it is working on Android. 
Any ideas?

**Comment by ddutchie** [comment]
Thanks! 

The browser does not present the loopback response HTML, but the app finishes the request.

**Comment by Elringus** [comment]
I've published a [new release](https://github.com/Elringus/UnityGoogleDrive/releases/tag/v0.20-alpha) with the fixes for both Android and iOS authentication issues. Please refer to the project's readme to find out how to configure the plugin to work on these platforms.

**Comment by ddutchie** [comment]
Great, Thanks! 

The only issue I am facing is that my bundle id for my app contains some Capital letters. As this app is already published there is no way to correct this. Is there a workaround so it could still work?

**Comment by ddutchie** [comment]
Great. I'll try that. Thanks again

**Comment by Elringus** [comment]
Can you please verify that it's working when you set original bundle id to lowercase (just to be sure that the issue is not with something else).

**Comment by ddutchie** [comment]
it is, as soon as bundle Id is lowercase it works.

**Comment by Elringus** [comment]
Ok, thanks for checking. I've created a new issue (#27) and will try to remove that requirement for the app id to be lowercased.

**Comment by Elringus** [comment]
I think I've actually found a temporary workaround for this. I've changed the requested redirect URI so that it will always use lower-cased app id and now the trick with adding lower-cased app id to the Supported URL Schemes list should work (it did in my test project, at least).

**Comment by ddutchie** [comment]
Great, that works!! 
Good job.
