### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by TwerkyMan** [Elringus/UnityGoogleDrive#26]
Hello. I have downloaded the latest version of this plugin and did all the steps to make it work on android. The problem is, as soon as i try to login with Google Drive, my app jus crashes. I don't know what to do. Thanks in advance!

**Comment by Elringus** [comment]
Make sure you've downloaded all the native dependencies. Your `Plugins/Android` folder should look like that: 
![](https://i.gyazo.com/8ce9d0b9ad7c45093b3c282843f3b1df.png)

If it won't help, please provide android log at the moment when the app crashes. You can access the log with [adb](https://developer.android.com/studio/command-line/adb) utility.

**Comment by TwerkyMan** [comment]
Alight, I downloaded the missing files, but now i get this error when i try to build the app.

CommandInvokationFailure: Unable to convert classes into dex format.
C:\Program Files\Java\jdk1.8.0_171\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:\Users\Vartotojas\AppData\Local\Android\sdk\tools" -Dfile.encoding=UTF8 -jar "D:\2018.2.6f1\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoIcsImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoStubImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatJellyBeanMr2;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/animation/AnimatorCompatHelper;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/animation/AnimatorListenerCompat;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/animation/AnimatorProvider;

**Comment by TwerkyMan** [comment]
Sorry, my mistake. I deleted some other plugin that caused this. Now the authentication starts on android, but when it finishes, it redirects to google.com. When i get back to my app, nothing has changed. It means that the request wasn't done?

**Comment by Elringus** [comment]
Most likely the custom URI scheme is not mapped correctly. Make sure your application ID is all lower cased and equals to the one you've set as a bundle ID in the console app settings.

**Comment by TwerkyMan** [comment]
In Unity my bundle ID has uppercase letters. Should i make that lowercase or is it enough to make it lowercase just in credentials?

**Comment by TwerkyMan** [comment]
One more question though, does it matter what build system i use? (Internal/Gradle)

**Comment by Elringus** [comment]
The app id should be lower cased both in the editor and in the credentials; guess I should update the FAQ to make it clear. The build system shouldn't matter, though I've only tested it on Gradle.

**Comment by TwerkyMan** [comment]
When i set my editor bundle ID to lowercased, my phone detects it as an entirely different application. Is there a way to use this plugin without changing my original ID (lowercased and uppercased)?

**Comment by Elringus** [comment]
Currently not (at least, for Android), but I'll try to think something out.

**Comment by TwerkyMan** [comment]
Thank you really much :)

**Comment by Elringus** [comment]
As a temporary workaround you can try to set the app id manually in `UnityGoogleDrive/Plugins/com.elringus.unitygoogledriveandroid.aar (unzip it) /AndroidManifest.xml`. Just replace `${applicationId}` with your application ID (lower cased).

**Comment by TwerkyMan** [comment]
Thanks for the support. I got it working and oh my god it even redirects back to my application when authentication is finished. You sir did a really good job on this. :)
