### ISSUE TITLE
Have any way to login my account in other app via code?

### ISSUE THREAD

**Issue by popeyaho** [Elringus/UnityGoogleDrive#3]
Hi, this is great, so can I using this API for storage file in my game, can log in my account to any device thought my info in code, don't need to log in via a browser. Thanks so much for the git!

**Comment by Elringus** [comment]
You can store any files on the drive as long as user has enough space quota. To access the Drive API user have to complete OAuth procedure, which requires opening a browser window to login and allow the app to access their drive. This limitation is enforced by Google for security reasons; more info here: https://developers.google.com/identity/protocols/OAuth2
