### ISSUE TITLE
Malformed multipart body

### ISSUE THREAD

**Issue by HerotechDevs** [Elringus/UnityGoogleDrive#30]
As of 07/11 something must have changed in the google drive api or backend since any upload (either creation or update) is returning a malformed multipart body error.

This didn't occur yesterday, or even this morning

**Comment by HerotechDevs** [comment]
This is getting weird, yesterday it started working again for a couple of hours and now it is failing once more

**Comment by HerotechDevs** [comment]
I found this, it might be related

https://stackoverflow.com/questions/52844182/getting-malformed-multipart-body-when-trying-to-upload-video-to-youtube

**Comment by Elringus** [comment]
I don't think they've dropped the multipart upload requests. At lest, they're still in the docs: https://developers.google.com/drive/api/v3/multipart-upload But you can try to use resumable uploads, maybe they'll work: https://github.com/Elringus/UnityGoogleDrive#is-it-possible-to-downloadupload-large-files-in-chunks-to-reduce-memory-usage

**Comment by HerotechDevs** [comment]
Yes, just thought about that myself as the link I provided the guy solved it that way.

It is working now again and changing from multipart to resumable was really easy.

Is the multipart working on your end?

**Comment by Elringus** [comment]
It's not. Seems like something indeed changed on the server side.

**Comment by Elringus** [comment]
Looks like Google has made the validation of the multipart bodies more strict. I've had to manually compose the body, preserving all the new lines and spaces, before it finally accepted the request. The multipart uploads in the latest release should work fine now: https://github.com/Elringus/UnityGoogleDrive/releases/tag/v0.22-alpha

**Comment by HerotechDevs** [comment]
Thank you =)
