### ISSUE TITLE
Resumable uploads malformed body

### ISSUE THREAD

**Issue by HerotechDevs** [Elringus/UnityGoogleDrive#32]
Same as for the multipart issue we had a few days ago now they went on to screw things with resumable uploads. just wanted to let you know

**Comment by Elringus** [comment]
Well, it's working for me. Make sure you're using the latest release and check out this test script: https://github.com/Elringus/UnityGoogleDrive/blob/master/Assets/Scripts/TestFilesCreateResumable.cs

**Comment by HerotechDevs** [comment]
Yes sorry didn't update, was still using the old version, although I found a bug in the newer one, you are adding a new line or space symbol at the end of the file after uploading to the drive

I just found this out, I was uploading my files first then I run the script another time and if the hashes match no update is necessary, and it is wrong for every file

I opened the files with a text editor and noticed that the file I downloaded from the drive had 1 extra line at the end could you please look into this? 


Da: "Artyom Sovetnikov" notifications@github.com
A: "Elringus/UnityGoogleDrive" UnityGoogleDrive@noreply.github.com
Cc: "HerotechDevs" a.centili@herotechnology.it,"Author" author@noreply.github.com
Data: Tue, 13 Nov 2018 03:07:03 -0800
Oggetto: Re: [Elringus/UnityGoogleDrive] Resumable uploads malformed body (#32)


Well, it's working for me. Make sure you're using the latest release and check out this test script: https://github.com/Elringus/UnityGoogleDrive/blob/master/Assets/Scripts/TestFilesCreateResumable.cs

**Comment by HerotechDevs** [comment]
I reverted also from resumable to the normal multipart update. and the multipart is the one causing the issues since I just reverted back to resumable and it is working as intended

**Comment by Elringus** [comment]
Good catch! I've removed the extra new line in the latest release: https://github.com/Elringus/UnityGoogleDrive/releases/tag/v0.23-alpha
