### ISSUE TITLE
iOS  Authentication Error

### ISSUE THREAD

**Issue by Maku-Simone** [Elringus/UnityGoogleDrive#36]
I started working with his SDK and it worked perfectly for the editor and Android, however when I tried using it in iOS everything died.
It calls the login screen, an when you are supposedly logged, it redircets you to Google instead to the redirect uri, i. e  the one that says "return to the app"
Also 2 errors are displayed in the console:

#1 
UnityGoogleDrive: OAuth authorization error: Error: The Operation coudldn't be completed (org.openid.appauth.general error-4.)
UnityEngine.DebugLogError(Object) 
UnityGoogleDrive.IOSAccessTokenProvider.HandleResponse(string)

#2 
UnityGoogleDrive: Failed to execute authorization procedure. Check application settings and credentials.
UnityEngine.DebugLogError(Object) 
UnityGoogleDrive.AuthController.HandleAccessTokenProviderDone(IAccessTokenProvider)

**Comment by Elringus** [comment]
Make sure your application ID is lower-cased (both in the editor and in the credentials) and you're using the latest appauth libs (https://github.com/Elringus/UnityGoogleDrive/blob/master/Assets/UnityGoogleDrive/Editor/Dependencies.xml#L3). If it won't help, please specify which iOS you're using.

**Comment by Elringus** [comment]
Actually, try also setting ipod to ver `1.0.0.beta1`: https://github.com/Elringus/UnityGoogleDrive/blob/master/Assets/UnityGoogleDrive/Editor/Dependencies.xml#L6

**Comment by Maku-Simone** [comment]
Didn't work :c

**Comment by Maku-Simone** [comment]
> 
> 
> Make sure your application ID is lower-cased (both in the editor and in the credentials) and you're using the latest appauth libs (https://github.com/Elringus/UnityGoogleDrive/blob/master/Assets/UnityGoogleDrive/Editor/Dependencies.xml#L3). If it won't help, please specify which iOS you're using.

10.3.3

**Comment by Maku-Simone** [comment]
This is what I have in my podfile, I've also tried adding things like GMTAuth or GoogleDriveClientForREST but no success
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'Unity-iPhone' do
	pod 'Firebase/Auth'
	pod 'Firebase/Core'
	pod 'Firebase/Messaging'
	pod 'AppAuth'
	pod 'GoogleSignIn’
	pod 'TesseractOCRiOS', '4.0.0'

end

**Comment by Elringus** [comment]
Hm, maybe it's conflicting with some other libs? Can you try to run a clean project with the latest appauth version, but without any other dependencies or scripts (you can use the test scripts from this project)?

**Comment by Maku-Simone** [comment]
Also the project is built using .net 3.5 Equivalent, could that be a problem? It works perfectly on Android but iOS keeps with those damn errors and redirecting to Google.com instead of the redirect uri.

**Comment by Elringus** [comment]
.net 3.5 shouldn't be problem, but you can try building it with 4.x just in case.

**Comment by Maku-Simone** [comment]
I tried with .NET 4.x  but had no success, after it sends me to the browser, and lets me choose the account, after 10 - 20 seconds it sends me to Google.com, skipping the "Google Will access to your data", etc screen

**Comment by Elringus** [comment]
Have you also tried with the new clean project and latest appauth version?

**Comment by Maku-Simone** [comment]
With the latest appauh is still the same

**Comment by Maku-Simone** [comment]
I finally managed a solution for this.
Here https://github.com/Elringus/UnityGoogleDrive/blob/master/Assets/UnityGoogleDrive/Runtime/Authorization/AuthController.cs#L33 I replaced that line with "LoopbackAccessTokenProvider4IOS(settings);"
And in the new class "LoopbackAccessTokenProvider4IOS", which is a copy LoopbackAccessTokenProvider(), I emoved the "if" statement at https://github.com/Elringus/UnityGoogleDrive/blob/master/Assets/UnityGoogleDrive/Runtime/Authorization/LoopbackAccessTokenProvider.cs#L135
After that it worked :3

**Comment by Elringus** [comment]
Well, I've used the loopback scheme on mobiles initially, but there were a lot of reports of it randomly not working on different devices/os versions; although, it doesn't redirect user back to the app after auth. But I'm glad you were able to make it work!
