### ISSUE TITLE
Security notice from Google

### ISSUE THREAD

**Issue by TwerkyMan** [Elringus/UnityGoogleDrive#38]
Hello. I have a rather weird question. Every time I log in using this plugin I get a security notice in my gmail telling me someone logged into my account when other apps that use authentication with Google don't get this behavior. Is it possible to remove these notices? Thanks in advance.

**Comment by Elringus** [comment]
You have to approve the application via the google developer console.

**Comment by TwerkyMan** [comment]
Thanks. I figured it out.
