### ISSUE TITLE
Is there Logout function?

### ISSUE THREAD

**Issue by natsupy** [Elringus/UnityGoogleDrive#4]
Hi, in this SDK have a function for logout after Auth? I was tested but I can't found it, can you help!?

**Comment by Elringus** [comment]
Hi, When authenticating access and refresh tokens are stored in player prefs with the following path:
```
"GoogleDriveAccessToken" for access token and
"GoogleDriveRefreshToken" for refresh token.
```
You can use `PlayerPrefs.DeleteKey` to delete them whenever you wish, which will force user to repeat login on the next request to the API.
