### ISSUE TITLE
I Want Load And Play Video File From GoogleDrive. How can i do it? Can you give me example?

### ISSUE THREAD

**Issue by kyoshyro86** [Elringus/UnityGoogleDrive#41]

**Comment by kyoshyro86** [comment]
I Want Load And Play Video File From GoogleDrive. How can i do it? Can you give me example?

**Comment by Elringus** [comment]
Check out the FAQ and `Assets/Scripts` folder for examples.

**Comment by kyoshyro86** [comment]
I don't see example loading Video. Please tell me which file can load in Assets/Scripts. Thanks

**Comment by Elringus** [comment]
Not sure there is one exactly for video, but you can figure it out using other examples. As for playing the video, google for unity tutorials on that.

**Comment by kyoshyro86** [comment]
@Elringus Thank so much, i tried it and search on google but it's not working with googledrive video. I'm using VideoPlayer in unity for loading Video. Can you send me example for it.

**Comment by Elringus** [comment]
With which step do you have issues (and what exactly the issues are)? Were you able to download byte[] representation of the video file?
