### ISSUE TITLE
CreateRequest bug

### ISSUE THREAD

**Issue by HerotechDevs** [Elringus/UnityGoogleDrive#42]
Creating a file with "GoogleDriveFiles.CreateRequest" creates a file with 2 additional bytes compared to "GoogleDriveFiles.ResumableCreateRequest"

I suspect the issue is with CreateRequest as updating the file with both UpdateRequest and ResumableUpdateRequest yield the same hash after upload as the ResumableCreateRequest.

As a side note, I would be happy to use the ResumableCreateRequest, but the response data when creation is finished is only a string and I need to get the webContentLink (which can be fetched with CreateRequest), the ResponseData field is a string only which contains information on how to resume the upload

**Comment by Elringus** [comment]
Does those 2 bytes really breaks anything? I mean, check the tests and examples in the project for creating a file, they were working fine for me.

**Comment by HerotechDevs** [comment]
I have about 1gb of files that get updated on a weekly basis.

After I created them some can get modified, I check for md5 hash and the first time around they all differ so all files get reuploaded, after that the hashes will all match.

Basically every file that gets created once with the CreateRequest will be reuploaded later on.

I will try to get around the issue somehow, I just need to avoid using the standard CreateRequest and use the resumable one, although with the resumable request I must take an additional step to get the file metadata from the drive.

**Comment by HerotechDevs** [comment]
Sorry for wasting your time, I found the issue, someone uploaded old files of your plugin on the repo (different line endings and discarded plugin update changes) and it totally messed things up.

Said person is currently being whipped
