### ISSUE TITLE
Helpers.FindFilesByPathAsync Not Returning New Files

### ISSUE THREAD

**Issue by fisher-bai** [Elringus/UnityGoogleDrive#44]
I'm using Helpers.FindFilesByPathAsync to return a list of files from a specific folder on my Google Drive. At first it seemed to be working just fine, returning every file in the folder. Then I created a new file within the folder, and it does not recognize this new file. I've waited >24 hours assuming Google Drive APIs have some kind of delay, and yet the file is still not being picked up.

When I delete or move an older file from within the folder it is no longer picked up, and if I turn on the trash flag it will pick up old deleted files, but it will not pick up any new files. I also tried making exact copies of old files, and still no luck.

Is there a local cache that UnityGoogleDrive makes that I'm unaware of?

**Comment by Elringus** [comment]
> Is there a local cache that UnityGoogleDrive makes that I'm unaware of?
Not that I’m aware of.

I've just checked the built-in test and it seem to pick up new files just fine. Maybe the issue is with some custom code you're using?

**Comment by fisher-bai** [comment]
@Elringus I am able to reproduce with the code used in the test scene. I'm still only seeing 2 files (ones that previously existed), and not seeing any new ones (there are 5 in the same folder). I can even modify the existing ones and see the updated contents, which is strange. It just seems like the new ones are being completely ignored. I'm the only one with access to the drive folder I am using.

Here's the code I'm using from the test scene.
`
private Dictionary<string, string> results;

        private void Awake()
        {
            FindFilesByPathAsync("My/Drive/Path/");
        }

        public async void FindFilesByPathAsync(string path)
        {
            var files = await Helpers.FindFilesByPathAsync(path, false, new List<string> { "files(id, name, size, mimeType, modifiedTime)" });
            BuildResults(files);
        }

        private void BuildResults(List<File> fileList)
        {
            if (fileList.Count == 0) { results = new Dictionary<string, string> { [string.Empty] = "Non files found." }; return; }

            results = new Dictionary<string, string>();

            foreach (var file in fileList)
            {
                var fileInfo = string.Format("Name: {0} Size: {1:0.00}MB '{2}' Modified: {3:dd.MM.yyyy}",
                    file.Name,
                    file.Size * .000001f,
                    file.MimeType,
                    file.ModifiedTime);
                results.Add(file.Id ?? "Failed", fileInfo);
            }
            foreach (string result in results.Values)
            {
                Debug.Log(result);
            }
        }
`

**Comment by fisher-bai** [comment]
I was manually adding files, and expecting it to get picked up. As it turns out the file must be created by the authorized app. Misunderstanding on my part. Closing.

**Comment by Elringus** [comment]
Well, I've tested it by manually dropping files to the drive via browser and they were picked up. I guess standalone clients should behave similarly. Not sure how else is possible to add the files to the drive (without an authorized client).

**Comment by MattLichter** [comment]
The issue had to do with [authorization scope](https://developers.google.com/drive/api/v2/about-auth).  The OP was using `auth/drive.file` scope, which means the app could only see files that it had created itself.  Files added via the browser are not visible to the app, by design.  So everything was working exactly as it should.

**Comment by Elringus** [comment]
Ah, I see. Thanks for the info! Will mention that in the readme.
