### ISSUE TITLE
Running Example code to test configurations

### ISSUE THREAD

**Issue by harrisonmount** [Elringus/UnityGoogleDrive#45]
Hi!
I am currently configuring your package to eventually upload data from a VR application to google drive. Are there example scenes / scripts I can run (or a tutorial to follow) to test to see if I have installed correctly?

Thanks,
Harrison

**Comment by Elringus** [comment]
Hi! Sure, check the `Scenes` and `Scripts` folders in the repo project.

**Comment by harrisonmount** [comment]
Okay thank you. Is there a reason the UnityGoogleDrive-master folders are not a part of the package import of UnityGoogleDrive.unitypackage? I tried importing the FilesCreate Scene but has two missing script sections. I am new to unity if you couldn't tell...

**Comment by harrisonmount** [comment]
I ran it with the two testfilescreate files and it worked but no keyboard input in the game window

**Comment by Elringus** [comment]
Just clone or download this project and open it with the Unity editor.
