### ISSUE TITLE
Uploading a file.

### ISSUE THREAD

**Issue by Basuvg** [Elringus/UnityGoogleDrive#47]
hi there, i m facing issue with uploading a png file to drive. I have followed instructions from the link (https://github.com/Elringus/UnityGoogleDrive). when i click upload nothing working. i have targeted this app for android. below is my script attached please suggest for solution.
this is my id - basavaraj.g@ziniostech.com

[UploadFile.txt](https://github.com/Elringus/UnityGoogleDrive/files/3550597/UploadFile.txt)

**Comment by Elringus** [comment]
Check out the examples in the repository project, I think there was one for uploading an image.

**Comment by Basuvg** [comment]
I have already tried the example project with "filewrite" scene.

Thank you

**Comment by Basuvg** [comment]
hi there, can any one reply my above question.. i m in need to work on this

**Comment by Elringus** [comment]
I'm not sure what's the problem. Have you tried the upload example I've mentioned before? If it's not working for you, make sure you've setup the google app correctly.

**Comment by Basuvg** [comment]
i have tried it in editor. after uploading it throw me error
Error: redirect_uri_mismatch

**Comment by Elringus** [comment]
That means the google app is not setup correctly.

**Comment by Basuvg** [comment]
hi there i have resolved the issue with setup.  now the problem is i have created android build but how can i give a path to the file and i m using filescreate scene. i m giving path like this 
/storage/emulated/0/WhatsApp/Media/WhatsAppImages/IMG-20190830-WA0001.jpg  in my android mobile but its not working

**Comment by Basuvg** [comment]
its working in editor

**Comment by Basuvg** [comment]
"upload to root" button click and "upload to appdata " button click not happening in android build
