### ISSUE TITLE
Redirecting to google.com after allow access

### ISSUE THREAD

**Issue by FaresMoukaddem** [Elringus/UnityGoogleDrive#48]
I have followed all the documentation and it works perfectly on the unity editor. But on an android device, it asks for access, and if i press allow it redirects me to google.com rather than the loopback uri. I made sure my package name is all in lowercase. Some help would be very appreciated.

**Comment by Elringus** [comment]
Use adb utility to access the device log and find out the reason it fails with the redirect. It could be an outdated auth lib or an issue in the auth middleware.

**Comment by FaresMoukaddem** [comment]
After i press allow and it redirects to google.com nothing is logged, but if i press the X button to go back to the app the log shows this: 
Exception: No such proxy method: UnityGoogleDrive.AndroidAccessTokenProvider+OnAuthorizationResponseListener.onAuthorizationResponse(System.Boolean,UnityEngine.AndroidJavaObject,System.String,System.String,System.String)

But the same error is logged if i press X without giving any permissions

**Comment by FaresMoukaddem** [comment]
Where you able to figure out whats going on?

**Comment by hippogamesunity** [comment]
Hello! I have the same issue.

**Comment by hippogamesunity** [comment]
Finally got it working after applying this workaround.
![image](https://user-images.githubusercontent.com/7318172/64709750-75b2b980-d4bf-11e9-8a91-571b7304f218.png)
Hope it will be fixed auomatically in next updates) Or at least added to FAQ section)

**Comment by Elringus** [comment]
Right, most likely that's an issue with the app ID. Also, check the new release, it now handles the auth cancellation correctly.
