### ISSUE TITLE
IOS 

### ISSUE THREAD

**Issue by Basuvg** [Elringus/UnityGoogleDrive#49]
hi there, i m built the app successfully for the android, while building for IOS i m stuck with the error "AppAuth.h" file not found. can you please help me out to resolve this issue.

**Comment by Basuvg** [comment]
when i build xcode project from unity, this file "com.elringus.unitygoogledriveios.mm" in plugins folder throwing error "AppAuth.h" file not found

**Comment by Elringus** [comment]
Most likely you didn't install the required native dependencies, please read the readme carefully.
