### ISSUE TITLE
Check if already authorised?

### ISSUE THREAD

**Issue by ddutchie** [Elringus/UnityGoogleDrive#5]
Hello @Elringus, Firstly thanks for the awesome project, easily integrated into my project.

I would like the user to click a button to authorise, but to hide this button if already authorised. Is it possible to check if authorised without sending the auth request?

**Comment by Elringus** [comment]
Hi, I don't think there is a special request for this in the Drive API, but you can try using tokeninfo endpoint like this: https://developers.google.com/identity/sign-in/web/backend-auth#calling-the-tokeninfo-endpoint 

Current access token is stored in the player prefs with the key "GoogleDriveAccessToken".

**Comment by ddutchie** [comment]
Glorious, will look into that. 

Another quick question, how do I push a file to a folder. 

I am assuming I need to make a folder using mimeType = 'application/vnd.google-apps.folder' ?

**Comment by ddutchie** [comment]
Its okay found it!
