### ISSUE TITLE
Just want to thank you =)

### ISSUE THREAD

**Issue by hippogamesunity** [Elringus/UnityGoogleDrive#52]
I'm making Pixel Studio, mobile pixel art editor. Hope I will be able to make cross platform gallery sync with your plugin soon!

BTW, you could add await examples as seems it works just fine with Unity 2019

var file = await GoogleDriveFiles.Download(id).Send();

It's much better than coroutines as you can return values when operation completes.

Also I had some difficulties with calculating check sum, I think you can add this feature to the plugin.

> public static string ComputeHash(byte[] inputBytes)
> {
> 	var hash = MD5.Create().ComputeHash(inputBytes);
> 	var stringBuilder = new StringBuilder();
> 
> 	for (var i = 0; i < hash.Length; i++)
> 	{
> 		stringBuilder.Append(hash[i].ToString("X2"));
> 	}
> 
> 	return stringBuilder.ToString().ToLower();
> }

**Comment by Elringus** [comment]
Hi, I'm glad you found the plugin useful! The async examples are already present in both readme and example scripts. I also prefer the async workflow, but a lot of Unity users are more accustomed to the co-routines, so I believe it's better to keep both options available.
