### ISSUE TITLE
Callback from authorization

### ISSUE THREAD

**Issue by hippogamesunity** [Elringus/UnityGoogleDrive#53]
Hi! My scenario:
- remove app data on Android (or perform Google Drive logout)
- make the first Google Drive call (List in my case), redirection to account selector happens
- close account selector window (without selecting an account)

Expected result:
- request.IsError = true, request.error = "User cancelled."

Actual result:
- nothing happens (my app is stucked on Loading... screen, UI is blocked)

Also I expect request.IsError = true if authorization process is cancelled anywhere later (wrong account, wrong password, no internet connection, permission denied, i.e. when we return to the app without success).

**Comment by hippogamesunity** [comment]
As a workaround:
- make GoogleDriveFiles.Get as a first request
- show progress and block UI after it will be completed (it will newer be completed if user closes login page, but my app will not stuck in this case)

**Comment by Elringus** [comment]
Hi, Thanks for the suggestion! I've published a new release, where the auth cancellations on Android are now properly handled, returning "OAuth authorization error".
