### ISSUE TITLE
Distribution as UnityGoogleDrive.unitypackage was removed

### ISSUE THREAD

**Issue by hippogamesunity** [Elringus/UnityGoogleDrive#55]
As I see there is no more option to get UnityGoogleDrive.unitypackage, at the same time it's the most simple way to import assets for most developers. I'm unable to install the package with Unity 2018.4.9f1 (64-bit). I suppose I should install git, right? But I've newer used it before, I use GitHub.
![image](https://user-images.githubusercontent.com/7318172/65255958-6fe45600-db07-11e9-9619-121c51c5c42b.png)

So my suggestion is to leave a link to UnityGoogleDrive.unitypackage to allow more developers to try your asset without questions like "how to install it?".

**Comment by Elringus** [comment]
Afaik, Unity is going to add an option to install git packages via the package manager window soon. For the time being, you can just directly download the package from the repo.

**Comment by hippogamesunity** [comment]
Will you consider publishing your asset on the Asset Store maybe?) I believe you are interested in getting more users of your asset)

**Comment by hippogamesunity** [comment]
Maybe even as a paid asset as I do)))

**Comment by Elringus** [comment]
I'm afraid I can't afford the time required to provide proper support for this plugin on the Asset Store, so no plans for publishing there atm.
