### ISSUE TITLE
What is minimum Android SDK?

### ISSUE THREAD

**Issue by hippogamesunity** [Elringus/UnityGoogleDrive#56]
I was testing your plugin on old devices and it crashes on Galaxy Tab 10.1 with Android 4.4.2.
This happens when redirecting to OAuth. Unfortunately, this device doesn't connect to my PC for some reason and it has no root, so I'm unable to get crash logs from it.
I will check Android 5, 6 and 7 tomorrow.

**Comment by Elringus** [comment]
Most likely this is a limitation of the native auth lib: 

> AppAuth supports Android API 16 (Jellybean) and above. Browsers which provide a custom tabs implementation are preferred by the library, but not required. Both Custom URI Schemes (all supported versions of Android) and App Links (Android M / API 23+) can be used with the library.

**Comment by hippogamesunity** [comment]
Btw I've checked it on Android 6 an 7, it works. I think you could add the requirement Android 6. Maybe even Android 5, but I don't have it.

**Comment by hippogamesunity** [comment]
net.openid:appauth supports API 16+, so the issue can be in another place.
https://github.com/openid/AppAuth-Android
![image](https://user-images.githubusercontent.com/7318172/65372885-ba3c1300-dc7e-11e9-8de0-699e1a2d5caa.png)

**Comment by Elringus** [comment]
The only other native android stuff used by the plugin is the auth client: https://github.com/Elringus/UnityGoogleDriveAndroid Maybe it's the one adding the limitation.

**Comment by hippogamesunity** [comment]
I've found a few issues with auth lib and Android version:
https://github.com/openid/AppAuth-Android/issues/464
https://github.com/openid/AppAuth-Android/issues/291

Also there is an issue related to Samsung browser:
https://github.com/openid/AppAuth-Android/issues/219

I will try to get crash logs...
