### ISSUE TITLE
Cannot install the iOS dependencies on windows

### ISSUE THREAD

**Issue by GuillermoDoradoVide** [Elringus/UnityGoogleDrive#58]
Installed ruby, curl and cocoapods. Then build the XCodeToBuild project with unity. When I try to launch command 'pod install' this messages shows: 
"A dependency with an external source may not specify version requirements (Google-Mobile-Ads-SDK)."
The content on the podFile:
```
source 'https://cocoapods.mycompany.com/Specs'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/CocoaPods/Specs'
platform :ios, '9.0'

target 'Unity-iPhone' do
  pod 'AppAuth', '~> 1.1.0'
  pod 'Google-Mobile-Ads-SDK', '~> 7.0', :path => 'C:\Users\Guillermo\Documents\TRABAJO\ECOSIM\ECOSim\google-mobile-ads-sdk'
end
```

**Comment by Elringus** [comment]
I'm not sure it's possible under windows, use macos.

**Comment by ephb** [comment]
It is not possible currently in Windows.
If macOS is not an option Unity Cloud Build should also work as it has support for CocoaPods.
