### ISSUE TITLE
iOS - Auth confirmation dialog disappears

### ISSUE THREAD

**Issue by FredrikHa** [Elringus/UnityGoogleDrive#63]
When the iOS device tries to show the authentication dialog box it disappears after a few milliseconds. Every other native dialog is working fine. Only this one with the "Continue" button.

I have tried on iOS 13.1.2 and 13.3, with no luck.
Unity 2019.2.17f1

In the editor it works fine. It opens the webpage and authentications is fine. Uploading files works as well.
Everything works fine using iOS 12.0.

Any ideas?

**Comment by Elringus** [comment]
It could be an issue due to an outdated iOS native auth library; make sure you're using the latest one.

**Comment by skoteskote** [comment]
I'm also getting stuck on this issue. Sorry, I'm kinda new to these things, but where would the outdated iOS native auth library be located?
