### ISSUE TITLE
Oculus Quest: OAuth Error

### ISSUE THREAD

**Issue by PhilippKuzmenko** [Elringus/UnityGoogleDrive#65]
Oculus Quest is running on Android, so I did "additional steps for iOS and Android" (Readme.md).

When user tries to upload file to Google Drive, browser opens and asks to log in for app "%appname%", after this step it redirects user to %generatedlink% with text "Please wait", after around 5 seconds of waiting it redirects to google.com and nothing happens, except 2 errors when app is open again:

Error 1:
"AndroidPlayer(Oculus_Quest@...) UnityGoogleDrive: OAuth authorization error: .
...
UnityGoogleDrive.AndroidAccessTokenProvider:HandleAuthorizationResponseOnUnityThread(Object) (at ...\Library\PackageCache\com.elringus.unitygoogledrive@...\Runtime\Authorization\AndroidAccessTokenProvider.cs:154)
UnityEngine.WorkRequest:Invoke() (at /Users/builduser/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:150)
UnityEngine.UnitySynchronizationContext:Exec() (at /Users/builduser/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:79)
UnityEngine.UnitySynchronizationContext:ExecuteTasks() (at /Users/builduser/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:104)
 
(Filename: D Line: 0)"

Error 2:
"AndroidPlayer(Oculus_Quest@...) UnityGoogleDrive: Failed to execute authorization procedure. Check application settings and credentials.
...
UnityGoogleDrive.AuthController:HandleAccessTokenProviderDone(IAccessTokenProvider) (at D:\UnityProjects\Avatar\Library\PackageCache\com.elringus.unitygoogledrive@...\Runtime\Authorization\AuthController.cs:61)
UnityGoogleDrive.AndroidAccessTokenProvider:HandleProvideAccessTokenComplete(Boolean) (at ...\Library\PackageCache\com.elringus.unitygoogledrive@...\Runtime\Authorization\AndroidAccessTokenProvider.cs:83)
UnityGoogleDrive.AndroidAccessTokenProvider:HandleAuthorizationResponseOnUnityThread(Object) (at ...\Library\PackageCache\com.elringus.unitygoogledrive@...\Runtime\Authorization\AndroidAccessTokenProvider.cs:155)
UnityEngine.WorkRequest:Invoke() (at /Users/builduser/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:150)
UnityEngine.UnitySynchronizationContext:Exec() (at /Users/builduser/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:79)
UnityEngine.UnitySynchronizationContext:ExecuteTasks() (at /Users/builduser/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:104)
 
(Filename: D Line: 0)"

**Comment by Elringus** [comment]
See: https://github.com/Elringus/UnityGoogleDrive/issues/43
