### ISSUE TITLE
missing APPAuth.h

### ISSUE THREAD

**Issue by AnandMulay** [Elringus/UnityGoogleDrive#69]
i'm getting appauth.h not found for unity framework. for latest unity package.

**Comment by AnandMulay** [comment]
for previous version there is no unity framework project under xcode projects , but now i can see extra project under xcode projects with name Unity framework and i get error for this project app auth file is not available though i have added pod files of appauth

**Comment by hippogamesunity** [comment]
The same here. Got this error after migrating from Unity 2019.2 to Unity 2019.4. Any solutions?

**Comment by hippogamesunity** [comment]
btw AppAuth is 1.4 at this moment, and looks like there was very imporant fix in 1.3.1
https://github.com/openid/AppAuth-iOS/releases

**Comment by yafarida** [comment]
![Снимок экрана 2020-06-19 в 21 01 23](https://user-images.githubusercontent.com/8149295/85166567-23819e80-b270-11ea-8ba3-35b2444f0879.png)

**Comment by yafarida** [comment]
https://docs.unity3d.com/Manual/StructureOfXcodeProject.html

**Comment by Elringus** [comment]
This is most likely due to Play Services Resolver not linking AppAuth library to Unity Framework target. Here is the corresponding issue on PSR repository: https://github.com/googlesamples/unity-jar-resolver/issues/333

**Comment by hippogamesunity** [comment]
I can confirm that updating PlayServicesResolver solved this problem.
https://github.com/googlesamples/unity-jar-resolver/tree/master/exploded/Assets

**Comment by simonpasi-ensam** [comment]
Newbie here... How does one update PlayServicesResolver?

**Comment by simonpasi-ensam** [comment]
nvm, I just imported the files from https://github.com/googlesamples/unity-jar-resolver/tree/master/exploded/Assets and a window opened up on its own, I clicked things and now the error is gone :)
