### ISSUE TITLE
Changes

### ISSUE THREAD

**Issue by Figbash** [Elringus/UnityGoogleDrive#7]
I apologize if this already exists but I am unable to find it. I am using UnityGoogleDrive to sync the files from an entire folder in google drive to the documents folder of a pixel art app and vice versa, and it mostly works perfectly.

The only flaw is I need to be able to see when the user deletes a file from google drive so I can delete it from the local documents folder.

Looking at the API, I believe I need to use the changes call with the date of the previous call to get this information correctly, but I don't see anything related to this in UnityGoogleDrive. Is there any chance you could add it?

**Comment by Elringus** [comment]
Well, you could try using the [Watch request](https://github.com/Elringus/UnityGoogleDrive/blob/master/Assets/UnityGoogleDrive/Runtime/API/GoogleDriveFiles.cs#L426), although I didn't test it myself and not even sure how it works. 

The [Changes API](https://developers.google.com/drive/v3/reference/changes) support is definitely something I would like to implement in the feature. I'll leave this issue open until it's done. Thank you for the suggestion!

**Comment by Figbash** [comment]
Ah, I believe that is for push notifications, which would be too complex a setup for what I need. Thanks for looking into changes, I believe I can work around not having it for now but changes would be a much less hacky solution. And thank you so much for the plugin, it is much appreciated!

**Comment by Elringus** [comment]
Changes API is now supported with the [latest release](https://github.com/Elringus/UnityGoogleDrive/releases/tag/v0.4-alpha).
