### ISSUE TITLE
request.Send().OnDone crashing on Android

### ISSUE THREAD

**Issue by zorksox** [Elringus/UnityGoogleDrive#70]
For some reason, this simple script causes my android app to crash.

    public class DriveTest : MonoBehaviour
    {
        private string result;
        private string fileId = "1h1zwtdrpL2IUm4kzMuGQS82plV_X2UXcp1WcS6SZ6oU";
        private GoogleDriveFiles.ExportRequest request;

        private void Start()
        {
            ExportDocument();  
        }

        private void ExportDocument()
        {
            request = GoogleDriveFiles.Export(fileId, "text/plain");
            request.Send().OnDone += file => GetContent(file); //crashes right here
        
        }

        void GetContent(UnityGoogleDrive.Data.File file)
        {
            result = Encoding.UTF8.GetString(file.Content);
        }
    }
Specifically, it crashes on this line: `request.Send().OnDone += file => GetContent(file); ` Most importantly, the application works as expected in the editor.  What am I missing?

**Comment by anderbggo** [comment]
Hi, did you find the solution? Thx
