### ISSUE TITLE
Can't get token

### ISSUE THREAD

**Issue by chenraiy** [Elringus/UnityGoogleDrive#75]
Hello, I have a problem about using  Oauth to get token. My project use upper-cased application ID, and I also use lowercased application ID in AndroidManifest.xml to get token. It worked. But, on Android 11, it seems has some trouble. I can't get token, when I login my google account, it don't return to app.

**Comment by Elringus** [comment]
See https://github.com/Elringus/UnityGoogleDrive#my-application-id-andriodios-is-mixed-cased-and-i-cant-change-it

**Comment by chenraiy** [comment]
I have already tried out the method in the link but still cannot work out.
I am not sure if this situation depends on the device. 
I tried on SONY, Samsung, and Nokia, and it worked well, but not for Redmi and Google(Only Google is Android 11, others are 9-10)

**Comment by Elringus** [comment]
Try updating the native auth library and check their repo for similar issues.
