### ISSUE TITLE
Conditionally exclude Json.NET

### ISSUE THREAD

**Issue by MattLichter** [Elringus/UnityGoogleDrive#76]
A lite version of Json.NET is currently embedded in the official package.  However, my project already includes a version of Json.NET for its own purposes.  When I use Unity Package Manager to import UnityGoogleDrive, I end up with two different Json.NET assemblies in the project.  They clash and prevent the project from compiling.

I need to be able to use my own version of Json.NET, as a lot of my own code relies on a different version than what is provided in the lite version here.  So I can't simply remove my own version of Json.NET.  I need to be able to exclude the UnityGoogleDrive's version.

This is easy enough to do if I'm using old-school unitypackage files.  But I don't know how this can be done with the new Unity Package Manager.  Can Unity Google Drive and Json.NET-lite be placed in separate packages?  Most people would then install both packages, but people like me could omit the Json.NET-lite package and provide their own.

@Elringus what do you think?  Can you think of any other solutions?

**Comment by MattLichter** [comment]
I suppose another option would be to use another branch (e.g. `package-no-thirdparty`) to publish the package without Json.NET-lite.  That way users can simply reference the package using one or the other:
- `https://github.com/Elringus/UnityGoogleDrive.git#package`
- `https://github.com/Elringus/UnityGoogleDrive.git#package-no-thirdparty`

This would be least disruptive to existing users and documentation.

**Comment by Elringus** [comment]
I'd rather switch to [System.Text.Json](https://docs.microsoft.com/en-us/dotnet/api/system.text.json), but we'll have to wait for Unity to support .NET 5 first.

**Comment by Elringus** [comment]
Actually, this was rather simple to solve: I've just wrapped the included jsonnet under the plugin namespace and disabled auto linking, so it should no longer cause conflicts with other jsonnets in the project. Let me know if it works for you.

**Comment by MattLichter** [comment]
@Elringus Excellent!  Your solution does indeed resolve the collision problems I was having!  My own version of Json.NET is now safely coexisting with your package.  Thanks! 👍 👍

**Comment by scott-higgs** [comment]
After upgrading project to Unity 2020.3.6f1, there is now a conflict between UGD's included Json.Net dll and one now included in Unity, but apparently not explicitly mentioned in Unity's dependecies manifest.  I was able to compile after removing the JsonNet-Lite folder from ```[project]/Assets/UnityGoogleDrive/ThirdParty/``` and adding ```"com.unity.nuget.newtonsoft-json": "2.0.0"``` to ```[project]/Packages/manifest.json```
