### ISSUE TITLE
Doesn't work on Oculus Quest 2

### ISSUE THREAD

**Issue by Propagant** [Elringus/UnityGoogleDrive#78]
I've been trying to run the GoogleDrive APi on Oculus Quest 2 without luck. I'm making a multiplatform application where user will have an access to his folders & files on Google Drive via application. It works very well on Android (mobile), iOS, Windows, MacOSX and Linux, but as I build the application for Oculus Quest, things get worse. 
The problem is, that when the app redirects me to the built-in Oculus browser and I choose a proper account in Google, the screen gets stuck at 'One moment please...'. After that nothing happens and google search engine appears without any notification that my app has been verified... Check the screenshot below
![IssueShot](https://user-images.githubusercontent.com/22862602/106529763-5882ee80-64eb-11eb-8f8a-b772b8ebbae2.jpg)

After getting back to the app, user is unable to continue due to the incompleted authentication.
**I would be really glad for any solution or help! I'm definitely willing to pay if any advanced solution is required. Thanks in advance.**

**Comment by Elringus** [comment]
Check out #43.

**Comment by Propagant** [comment]
Still nothing. I tried reinstalling all the required & latest android packages, especially for Oculus Quest 2. I also used the adb logcat, but no errors popped out. The auth process just ends on the Google webpage. If there's anyone who solved the GDrive for Oculus Quest issue, I would be glad for every response!

**Comment by twaddellberkeley** [comment]
@Propagant did you ever find a solution or even entirely different work around for this>

**Comment by Propagant** [comment]
> @Propagant did you ever find a solution or even entirely different work around for this>

Nope! Switched to the custom server based uploading...

**Comment by twaddellberkeley** [comment]
@Propagant  Dang, sorry to hear, do you have and rough guides or tutorials you followed for that?
