### ISSUE TITLE
AppAuth file not found

### ISSUE THREAD

**Issue by chriswattz** [Elringus/UnityGoogleDrive#80]
Hi,

i recently changed over to XCode 12 (Big Sur) and ios 14 on my Ipad.
I had a lot of builds for my app on iOS 12 and it worked well.

Now when i use the "pod install" command the data is written and i can see the AppAuth files but
the XCode build fails with the error "AppAuth file not found".

Cannot find the problem, anyone can help me ?

Thx

Chris

**Comment by markgrossnickle** [comment]
Same here. Any luck @chriswattz? 

I am able to build on Unity Cloud Build.  But when I try to build to the device via XCode I get the AppAuth issue, even after running Pod Install.

**Comment by FenrirGameStudio** [comment]
We're also experiencing this error. However, unlike you @markgrossnickle we cannot build via unity cloud build, we can only build manually.

**Comment by markgrossnickle** [comment]
Strange

I never sorted it out on my end. I ended up just focusing on Cloud build and avoiding the issue to complete the project.  Sorry

**Comment by ROBYER1** [comment]
> Hey guys : ) So we figured it out on our end, though not in the most glorious way : ) We added in the AppAuth.h that it's looking for manually and that sorted out the issue for us. I hope this helps someone else with this issue, best of luck!

Where did you find the actual AppAuth.h file? I can't find where it even is to add it myself!
