### ISSUE TITLE
Manifest merger failed : Attribute data@scheme at AndroidManifest.xml requires a placeholder substitution but no value for <appAuthRedirectScheme> is provided

### ISSUE THREAD

**Issue by tonismogames** [Elringus/UnityGoogleDrive#81]
I get this error when building android in Unity 2019.4.22f1

**Comment by tonismogames** [comment]
Nvm I fixed it by unchecking the use custom gradle in build settings.

**Comment by ROBYER1** [comment]
Is there a workaround to use this when custom gradle is in build settings? What if some people need it.

**Comment by ROBYER1** [comment]
For this I had to actually untick 'Patch AndroidManifest.xml option in Assets> External Dependency Manager > Android > Settings
