### ISSUE TITLE
Oculus Quest Build Issue.

### ISSUE THREAD

**Issue by twaddellberkeley** [Elringus/UnityGoogleDrive#87]
Hello,

I am using this library on the Oculus quest. In runtime for unity this plugin works great and pulls all the needed info. However at runtime for Oculus I get this error:

11-08 15:17:45.473 12494 12517 D Unity   : initOculus Java!
11-08 15:17:45.473 12494 12494 D Unity   : Oculus UI thread done.
11-08 15:17:45.502 12494 12517 E Unity   : UnityGoogleDrive: OAuth authorization error: .
11-08 15:17:45.502 12494 12517 E Unity   : 
11-08 15:17:45.502 12494 12517 E Unity   : UnityGoogleDrive: Failed to execute authorization procedure. Check application settings and credentials.
11-08 15:17:45.502 12494 12517 E Unity   : 
11-08 15:17:45.506 12494 12517 E Unity   : NullReferenceException: Object reference not set to an instance of an object
11-08 15:17:45.506 12494 12517 E Unity   :   at TestFilesList.BuildResults (UnityGoogleDrive.Data.FileList fileList) [0x0000b] in <478f66add8a74c17a9bbb0a4d4104207>:0 
11-08 15:17:45.506 12494 12517 E Unity   :   at UnityGoogleDrive.GoogleDriveRequestYieldInstruction`1[TResponse].HandleRequestDone (TResponse responseData) [0x0001f] in <b17032b1d4d844759d8c2bef8a115630>:0 
11-08 15:17:45.506 12494 12517 E Unity   :   at UnityGoogleDrive.GoogleDriveRequest`1[TResponse].CompleteRequest () [0x0001b] in <b17032b1d4d844759d8c2bef8a115630>:0 
11-08 15:17:45.506 12494 12517 E Unity   :   at UnityGoogleDrive.GoogleDriveRequest`1[TResponse].HandleAccessTokenRefreshed (System.Boolean success) [0x00026] in <b17032b1d4d844759d8c2bef8a115630>:0 
11-08 15:17:45.506 12494 12517 E Unity   :   at UnityGoogleDrive.AuthController.HandleAccessTokenProviderDone (UnityGoogleDrive.IAccessTokenProvider provider) [0x00042] in <b17032b1d4d844759d8c2bef8a115630>:0 
11-08 15:17:45.506 12494 12517 E Unity   :   at UnityGoogleDrive.AndroidAccessTokenProvider.HandleProvideAccessTokenComplete (System.Boolean error) [0x00016] in <b17032b1d4d844759d8c2bef8a115630>:0 
11-08 15:17:45.506 12494 12517 E Unity   :   at UnityGoogleDrive.AndroidAccessTokenProvider.Hand

I set up my android correctly, and even tried changing local host to 127.0.0.1

Is there anything I'm missing?

Thanks!

**Comment by twaddellberkeley** [comment]
And there was no answer provided in #43 #65 #78 . It is not a config error as I have gone through everything and it works on normal android phones. The issue has been pointed out on unity forums as well. Deep diving to see what can be done.

**Comment by twaddellberkeley** [comment]
https://github.com/firebase/quickstart-unity/issues/975 This seems to be part of it.

**Comment by twaddellberkeley** [comment]
Or could be this as well https://forums.oculusvr.com/t5/Quest-Development/Feature-Request-Allow-appps-to-be-launched-via-intent-filters/td-p/761475#latest
Intent filters do not seem to work on quest

**Comment by twaddellberkeley** [comment]
@Elringus I think the issue is rooted in not being able to move away from the program to the browser and back, what if there was an in game browser (https://assetstore.unity.com/packages/tools/gui/embedded-browser-55459)

**Comment by Elringus** [comment]
That is probably a bug with the native android auth library. Try updating it.

**Comment by twaddellberkeley** [comment]
Hey @Elringus, This is very much wrong and you should stop closing these issues, its a larger issue of compatibility for the quest, that could be solved through this platform if you actually took it seriously.
