### ISSUE TITLE
Upload file to a specific folder

### ISSUE THREAD

**Issue by anderbggo** [Elringus/UnityGoogleDrive#91]
Hi, I've been looking at the examples and I can't find anything about this.

Thx

**Comment by anderbggo** [comment]
Do I have to first send the file and then move it?

**Comment by anderbggo** [comment]
I just fixed it.

For those newbies like me, you have to copy the folder ID and use it as argument on files.Parent (similar to the example of file.create with appDataFolder)

**Comment by ROBYER1** [comment]
Did you have any issue with files being created at the root of your Gdrive even when the folder ID is provided in the file.Parent when on device? Works fine for me in Editor but on IOS the files upload to the root of my google drive instead of the folder specified as parent

**Comment by anderbggo** [comment]
> Did you have any issue with files being created at the root of your Gdrive even when the folder ID is provided in the file.Parent when on device? Works fine for me in Editor but on IOS the files upload to the root of my google drive instead of the folder specified as parent

Hi,

At the end I used the Google API instead. Is not difficult to use
