### ISSUE TITLE
Stops working on Android SDK 30

### ISSUE THREAD

**Issue by tonismogames** [Elringus/UnityGoogleDrive#93]
Works fine on Android SDK 29 or below. Google play store now requires SDK 30 or above and this plugin no longer works on it. It either crashes or freezes.

**Comment by Elringus** [comment]
Iirc, you can update the sdk versions by editing play services resolver manifest.

**Comment by Elringus** [comment]
Try bumping this to the latest appauth (https://github.com/openid/AppAuth-Android) release:

https://github.com/Elringus/UnityGoogleDrive/blob/master/Assets/UnityGoogleDrive/Editor/Dependencies.xml#L3

**Comment by tonismogames** [comment]
Thank You!I will try that
